# Copyright 2024 Holger Kluck
# This file run_highStatistic.mac is part of G4minWE.
#
# G4minWE is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# G4minWE is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with G4minWE. If not, see <http://www.gnu.org/licenses/>.
 
#Initialse Geant4
/run/initialize

#Increase verbosity
/control/verbose 1
/run/verbose 1
/event/verbose 0
/tracking/verbose 0

#Chose a gamma of 6 MeV as primar particle
/gps/particle ion
#Radium emanation = 222Rn
#see https://en.wikipedia.org/wiki/Radon
/gps/ion 86 222
/gps/pos/type Point
#z-position in absolute world coordiantes
#The vessel center coincide with the origin of coordinates
#+0.3/2 #Displacement of vaccum center with respect to vessel center
#-3.5/2 #Distance from vacuum center to bottom of vaccum
#+0.8   #Distacne from bottom of vaccum to bottom of foil
#+1.5/2 #Distacne from bottom of foil to center of foil
#As center for foil is align with source -> z-coordinate of source
#Given in units of 1.2cm
#->z=-0.05*1.2cm=-0.06cm
#Distance between center of vessel and source is one unit=1.2cm
/gps/pos/centre 2.4 0.0 -0.125 cm
#Isotropic
/gps/ang/type iso
#Nuclei at rest
/gps/energy 0 MeV

#Simulate 2 events, one primary particle per event
/run/beamOn 10000
